#Create a pod and expose port 5000
apiVersion: v1
kind: Pod
metadata:
  name: kandula-pod
  labels:
    app: backend
spec:
  containers:
    - image : sigalits/kandula-mid-prj:v1
      name: kandula
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      env:
        - name: FLASK_ENV
          value: development
        - name: AWS_DEFAULT_REGION
          value: us-east-1
      envFrom:
        - secretRef:
             name: kandula-secret
