apiVersion: v1
kind: Service
metadata:
  name: kandula-load-balancer
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30036
      protocol: TCP
