---
- name: install dependency
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: install python-consul
  pip:
    name: python-consul


- name: register jenkins-server with http port 8080
  consul:
    service_name: "{{ inventory_hostname }}"
    service_port: "8080" 
    interval: 10s
    http: http://localhost:8080/login
  notify: restart consul
  when : ( inventory_hostname  == 'jenkins-server' )

- name: register servers with  port 22
  consul:
    service_name: "{{ inventory_hostname }}"
    service_port: "22" 
    interval: 10s
  notify: restart consul
  when : ( inventory_hostname  != 'jenkins-server' )

- name: register elasticsearch with http port 9200
  consul:
    service_name: "{{ inventory_hostname }}-elasticsearch"
    service_port: "9200"
    interval: 10s
    http: http://localhost:9200/_cluster/health
    tags: ["logging"]
  notify: restart consul
  when : ( groups['elk'] is defined and inventory_hostname in groups.elk)

- name: register kibana with http port 5601
  consul:
    service_name: "{{ inventory_hostname }}-kibana"
    service_port: "5601"
    interval: 10s
    http: http://localhost:5601/status
    tags: ["logging"]
  notify: restart consul
  when : ( groups['elk'] is defined and inventory_hostname in groups.elk )