---
  - name: install dependency
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
  
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present



  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: install docker module for python
    pip:
      name: "{{item}}"
    loop:
      - docker
      - python-consul
      - requests
  
  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: pull and start nginx containar
    docker_container:
      image: nginx:stable
      name: nginx
      auto_remove: true
      state: started
      ports: 
        - "8080:80"

  - name: register nginx with an http check
    consul:
      service_name: webserver
      service_port: 8080
      interval: 10s
      http: http://localhost:8080
 