plugin: aws_ec2
regions: 
  - us-east-1
filters:
  tag:project:
    - Final

groups:
  consul_server: "'true' in tags.consul_server"
   #server: " 'true' in tags.opschool_server"
   #  ansible_ssh_private_key: /home/ubuntu/consul.key
  consul_agent: "'true' in tags.consul_agent"
  jenkins: "'jenkins' in tags.purpose"
  node_exporter: "'true' in tags.node_exporter"
  final_project: "'Final' in tags.project"
  psql : "'true' in tags.psql"

  #jenkins_server: "'true' in tags.consul_agent and 'true' in tags.jenkins-server"
  #ansible_ssh_private_key: /home/ubuntu/consul.key

anisble_ssh_user: ubuntu
instance-state-name : running
hostnames:
  - tag:Name
  - private-ip-address
compose:
  ansible_host: private_ip_address

