- name: Add GPG key
  apt_key:
    url: https://www.pgadmin.org/static/packages_pgadmin_org.pub

- name: Setup pgAdmin4 Stable repo
  apt_repository:
    repo: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bionic pgadmin4 main"
    update_cache: yes

- name: Install pgAdmin4
  apt:
    name:
      - pgadmin4-desktop
    update_cache: yes
    state: present

- name: Update pip3 package
  pip:
    name: pip
    state: latest

- name: Install psycopg2
  pip:
    name:
      - psycopg2-binary==2.9.3

- name: copy setup sql script
  copy:
    src: ./files/setup_db.sql
    dest: /home/ubuntu/
    owner: ubuntu
    mode: '0775'
  tags:
    - include_psql_role

- name: run sql script on rds db
  community.postgresql.postgresql_script:
    login_db: "{{ db_name }}"
    port: "{{ db_port }}"
    login_host: "{{ db_host}}"
    login_user: "{{ db_admin_user }}"
    login_password: "{{ db_admin_password }}"
    path: /home/ubuntu/setup_db.sql
    encoding: UTF-8
  tags:
    - include_psql_role
  ignore_errors: yes

- name: register external service kanduladb
  consul:
    service_name: "{{db_name}}"
    service_port: "{{db_port }}"
    service_address: "{{db_host }}"
    tags:
      - not_ec2
