---
- name: opsschool final project
  hosts:  final_project
  become: true

  vars:
    allow_world_readable_tmpfiles: true

  tasks:
    - name: include consul
      include_role:
       name: consul
      when: inventory_hostname in lookup('inventory_hostnames', 'consul_server:consul_agent')
    - name: include node_exporter
      include_role:
       name: node_exporter
    - name: include fileabeat
      include_role:
        name: filebeat
      when: inventory_hostname in groups.filebeat
    - name: include psql tasks
      include_role:
        name: psql
      when : ( groups['psql'] is defined and inventory_hostname in groups.psql )

