apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:797686858489:certificate/77f50a6c-acc1-4ba4-a99f-76ff5745b4b5
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    # Specifically create a NLB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Fixes issues with force ssl redirect
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    external-dns.alpha.kubernetes.io/hostname: grafana.sigalits.com
spec:
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  ports:
#    - name: http
#      port: 80
#      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000