create_consul_servers = true
create_jenkins_servers = false
jenkins_nodes_count = 0
create_consul_lb = true
create_lb = true
force_destroy = true
jenkins_key_name="sigal_jenkins_ec2_key"
create_rds = false
create_eks = true
eks_instance_types_1 = ["t3.medium"]
eks_instance_types_2 = ["t3.micro"]
eks_instance_count = 4
elk_instance_count = 0