create_consul_servers = false
create_jenkins_servers = false
jenkins_nodes_count = 0
create_consul_lb = false
#create_lb = false
force_destroy = true
jenkins_key_name="sigal_jenkins_ec2_key"
create_rds = true
create_eks = true
eks_instance_types_1 = ["t3.micro"]
eks_instance_types_2 = ["t3.micro"]
eks_instance_count = 2