#output "ec2_private_ip_kandula_instance" {
#  value = module.web-server.kandula_private_ips[*]
#}
#
#output "ec2_public_ip_kandula_instance" {
#  value = module.web-server.kandula_public_ips[*]
#}
#
#output "ec2_private_ip_database_instance" {
#  value = module.database.database_servers_ips[*]
#}

output "ec2_private_ip_consul_instance" {
  value = module.consul.consul_servers_ips[*]
}

output "ec2_private_ip_bastion_server" {
  value = module.bastion.bastion_servers_private_ips[*]
}

output "ec2_public_ip_bastion_server" {
  value = module.bastion.bastion_servers_public_ips[*]
}

output "Used_Availability_Zones" {
  value = local.azs
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = module.eks.cluster_name
}

output "oidc_provider_arn" {
  value = module.eks.oidc_provider_arn
}

output "Jenkins_nodes_ip" {
  value = aws_instance.jenkins-node[*].private_ip
}

output "consul_lb" {
  value = module.consul.lb_consul_dns
}

output "bastion_ip" {
  value = module.bastion.bastion_servers_public_ips[0]
}

output "Jenkins_alb" {
  value = data.terraform_remote_state.vpc.outputs.jenkins_alb
}

output "consul_alb" {
  value = module.consul.lb_consul_dns
}